#!/usr/bin/env python3
"""
Generate gravity deformation bins by running ANSYS Mechanical APDL in batch mode.

For each tilt angle θ (10°–80°, 20 bins default), runs a zero-bolt-height
static structural simulation with NLGEOM=ON, extracts the plate-local UY
displacement field, interpolates it onto the GS×GS render grid, and saves
gravity_{θ}deg.bin.

Prerequisites:
  - ANSYS Mechanical APDL (tested with v252)
  - License server running

Usage:
  # Generate 20-bin gravity data with current bolt layout
  python scripts/ansys_gravity.py --bolt-layout configs/bolt_layouts/7x5_default.json

  # Custom grid / angles
  python scripts/ansys_gravity.py --grid-size 32 --angles 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80
"""
import argparse
import json
import os
import re
import subprocess
import sys
import tempfile
import time
from pathlib import Path

import numpy as np
from scipy.interpolate import griddata

ROOT = Path(__file__).resolve().parent.parent

sys.path.insert(0, str(Path(__file__).resolve().parent))
import layout_utils

# ── ANSYS executable (v252) ──
ANSYS_EXE = "L:/Program Files/ANSYS Inc/v252/ansys/bin/winx64/ANSYS252.exe"

# ── Default gravity angles: 20 bins, denser at low angles (stronger NLGEOM) ──
DEFAULT_ANGLES = [10, 14, 18, 22, 26, 30, 34, 38, 42, 46,
                  50, 54, 58, 62, 66, 70, 73, 76, 78, 80]


def load_bolt_layout(path):
    """Load bolt layout configuration from JSON (all three forms, Phase 5.4)."""
    return layout_utils.load_layout(path)


def bolt_positions(layout):
    """Compute bolt (x,z) positions from layout config (row-major: z outer, x inner).

    Supports all three layout forms (grid / positions lines / free positions)
    via layout_utils (Phase 5.4)."""
    bx, bz = layout_utils.bolt_positions(layout)
    return list(zip(bx.tolist(), bz.tolist()))


def generate_apdl_input(layout, angle_deg, bolt_xy, output_file, work_dir,
                        nsubst="1,10,1"):
    """Generate ANSYS APDL input for gravity simulation at angle_deg.

    Models the plate TILTED about X-axis (matching Workbench GUI approach):
    - Plate corners use GUI convention: plate normal = (0, cosθ, +sinθ)
    - Gravity is always vertical: ACEL,0,9.81,0
    - Bolt nodes fixed (all DOF=0) for zero-height gravity-only sim
    - Output: 7-column CSV (x,y,z,ux,uy,uz,usum) matching train_data/ format

    Args:
        layout: bolt layout config dict
        angle_deg: tilt angle from horizontal (degrees)
        bolt_xy: list of (x, z) bolt positions in plate-local coordinates (m)
        work_dir: working directory for ANSYS scratch files

    Returns:
        (dat_path, node_csv_path)
    """
    W = layout["plate_width_m"]
    L = layout["plate_length_m"]
    t = layout["plate_thickness_m"]
    E = layout.get("youngs_modulus_pa", 7.0e10)
    nu = layout.get("poisson_ratio", 0.22)
    rho = layout.get("density_kg_m3", 2500)

    theta = np.radians(angle_deg)
    sin_t = np.sin(theta)
    cos_t = np.cos(theta)

    # Plate corners in global coords (tilted about X).
    # GUI convention: plate normal = (0, cosθ, +sinθ) in global coords.
    # When z_local=+hl (top edge), global Y=-hl*sin_t (below origin).
    # Matches train_data/APDL_pre.txt and Ansys Workbench GUI.
    hw, hl = W / 2.0, L / 2.0
    corners_global = [
        (-hw, -hl * sin_t,  hl * cos_t),   # -X, +Z (top edge, below origin)
        ( hw, -hl * sin_t,  hl * cos_t),   # +X, +Z
        ( hw,  hl * sin_t, -hl * cos_t),   # +X, -Z (bottom edge, above origin)
        (-hw,  hl * sin_t, -hl * cos_t),   # -X, -Z
    ]

    dat_path = os.path.join(work_dir, f"gravity_{angle_deg}deg.dat")
    node_csv = os.path.join(work_dir, f"node_dump_{angle_deg}deg.csv")

    lines = []
    lines.append(f"! Zero-bolt gravity: tilt={angle_deg}deg")
    lines.append(f"! Auto-generated by scripts/ansys_gravity.py")
    lines.append(f"! Approach: tilted plate + vertical gravity (matches Workbench GUI)")
    lines.append("")
    lines.append("/NOPR")
    lines.append("")
    lines.append(f"! ── Parameters ──")
    lines.append(f"W = {W}")
    lines.append(f"L = {L}")
    lines.append(f"thick = {t}")
    lines.append(f"E_mod = {E}")
    lines.append(f"nu = {nu}")
    lines.append(f"rho = {rho}")
    lines.append(f"ang = {angle_deg}")
    lines.append(f"nbolts = {len(bolt_xy)}")
    lines.append("")
    lines.append("/PREP7")
    lines.append("")
    lines.append("! ── Material & Element ──")
    lines.append("MP,EX,1,E_mod")
    lines.append("MP,NUXY,1,nu")
    lines.append("MP,DENS,1,rho")
    lines.append("ET,1,SHELL181          ! 4-node structural shell")
    lines.append("KEYOPT,1,3,2           ! incompatible modes (match Workbench GUI)")
    lines.append("R,1,thick")
    lines.append("")
    lines.append("! ── Geometry: 4-sided area ──")
    lines.append(f"K,1,{corners_global[0][0]:.6f},{corners_global[0][1]:.6f},{corners_global[0][2]:.6f}")
    lines.append(f"K,2,{corners_global[1][0]:.6f},{corners_global[1][1]:.6f},{corners_global[1][2]:.6f}")
    lines.append(f"K,3,{corners_global[2][0]:.6f},{corners_global[2][1]:.6f},{corners_global[2][2]:.6f}")
    lines.append(f"K,4,{corners_global[3][0]:.6f},{corners_global[3][1]:.6f},{corners_global[3][2]:.6f}")
    lines.append("A,1,2,3,4")
    lines.append("")
    ndiv_x = layout.get("mesh_ndiv_x", 64)
    ndiv_z = layout.get("mesh_ndiv_z", 48)
    lines.append(f"! ── Mesh: mapped quad mesh {ndiv_x}x{ndiv_z} (matching Workbench GUI) ──")
    lines.append("MSHAPE,0,2D             ! quad elements")
    lines.append("MSHKEY,1                ! mapped mesh (deterministic, matches GUI)")
    lines.append(f"LESIZE,1,,,{ndiv_x}           ! L1 (K1-K2): X-parallel, {ndiv_x} divs")
    lines.append(f"LESIZE,2,,,{ndiv_z}           ! L2 (K2-K3): Z-parallel, {ndiv_z} divs")
    lines.append(f"LESIZE,3,,,{ndiv_x}           ! L3 (K3-K4): X-parallel, {ndiv_x} divs")
    lines.append(f"LESIZE,4,,,{ndiv_z}           ! L4 (K4-K1): Z-parallel, {ndiv_z} divs")
    lines.append("AMESH,ALL")
    lines.append("")
    lines.append("! ── BC: NSEL near each bolt, then D (exact match of APDL_pre.txt) ──")
    lines.append(f"HALF_WIN=0.3")
    for i, (bx, bz_local) in enumerate(bolt_xy):
        gx = bx
        gz = bz_local * cos_t
        lines.append(f"NSEL,S,LOC,X,{gx:.6f}-HALF_WIN,{gx:.6f}+HALF_WIN")
        lines.append(f"NSEL,R,LOC,Z,{gz:.6f}-HALF_WIN,{gz:.6f}+HALF_WIN")
        lines.append(f"D,ALL,UX,0.0              ! fix translation only (match GUI, no rotation constraint)")
        lines.append(f"D,ALL,UY,0.0")
        lines.append(f"D,ALL,UZ,0.0")
        lines.append("ALLSEL,ALL")
    lines.append("")
    lines.append("! ── Solution ──")
    lines.append("/SOLU")
    lines.append("ANTYPE,STATIC")
    lines.append("NLGEOM,ON")
    lines.append("AUTOTS,ON              ! auto time stepping (match GUI)")
    lines.append(f"NSUBST,{nsubst}           ! initial,max,min substeps")
    lines.append("OUTRES,ALL,ALL")
    lines.append("PIVCHECK,0             ! disable pivot checking")
    lines.append("PRED,ON                ! predictor (match GUI)")
    lines.append("")
    lines.append("! Gravity: always vertical (global +Y direction)")
    lines.append("ACEL,0,9.81,0")
    lines.append("SOLVE")
    lines.append("FINISH")
    lines.append("")
    lines.append("! ── Post: 7-col CSV matching Workbench GUI format ──")
    lines.append("/POST1")
    lines.append("SET,LAST")
    lines.append("ALLSEL,ALL")
    lines.append("")
    lines.append("*GET,N_NODES,NODE,0,COUNT")
    lines.append("*GET,N_MIN,NODE,0,NUM,MIN")
    lines.append("")
    lines.append("*CFOPEN,'" + node_csv.replace('\\', '/') + "',,,")
    lines.append("*VWRITE,'x','y','z','ux','uy','uz','usum'")
    lines.append("%C,%C,%C,%C,%C,%C,%C")
    lines.append("")
    lines.append("nd = N_MIN")
    lines.append("*DO,idx,1,N_NODES,1")
    lines.append("  *GET,ux_val,NODE,nd,U,X")
    lines.append("  *GET,uy_val,NODE,nd,U,Y")
    lines.append("  *GET,uz_val,NODE,nd,U,Z")
    lines.append("  *GET,usum_val,NODE,nd,U,SUM")
    lines.append("  *VWRITE,NX(nd),NY(nd),NZ(nd),ux_val,uy_val,uz_val,usum_val")
    lines.append("  %12.6F,%12.6F,%12.6F,%14.9F,%14.9F,%14.9F,%14.9F")
    lines.append("  nd = NDNEXT(nd)")
    lines.append("*ENDDO")
    lines.append("*CFCLOSE")
    lines.append("")
    lines.append("FINISH")
    lines.append("/EXIT,NOSAVE")

    with open(dat_path, 'w') as f:
        f.write('\n'.join(lines))

    return dat_path, node_csv


def run_ansys(dat_path, work_dir, ansys_exe=ANSYS_EXE, timeout_s=600):
    """Run ANSYS MAPDL in batch mode.

    Returns True on success.
    """
    jobname = os.path.splitext(os.path.basename(dat_path))[0]
    cmd = [
        ansys_exe,
        "-b",                    # batch mode
        "-np", "4",              # 4 cores
        "-dir", work_dir,
        "-j", jobname,
        "-i", dat_path,
        "-o", os.path.join(work_dir, f"{jobname}.out"),
    ]
    print(f"  ANSYS: {' '.join(cmd[:2])} -j {jobname} ...")
    try:
        result = subprocess.run(cmd, cwd=work_dir,
                                timeout=timeout_s,
                                capture_output=True, text=True)
        if result.returncode != 0:
            # ANSYS often returns non-zero even on success; check for output file
            pass
        return True
    except subprocess.TimeoutExpired:
        print(f"  ERROR: ANSYS timed out after {timeout_s}s", file=sys.stderr)
        return False
    except FileNotFoundError:
        print(f"  ERROR: ANSYS not found at {ansys_exe}", file=sys.stderr)
        print(f"  Set ANSYS_EXE environment variable or edit ansys_gravity.py",
              file=sys.stderr)
        return False


def parse_node_output(csv_path):
    """Parse ANSYS *VWRITE CSV output: x,y,z,ux,uy,uz,usum.

    Returns: x_fea, z_fea, uy_fea arrays (global coords, m)
    """
    data = np.loadtxt(csv_path, delimiter=',', skiprows=1)
    if data.shape[1] < 7:
        raise ValueError(f"Expected 7 columns in {csv_path}, got {data.shape[1]}")
    x = data[:, 0]   # NX - global
    z = data[:, 2]   # NZ - global (already cos(θ)-compressed)
    uy = data[:, 4]   # UY - global
    return x, z, uy


def run_gravity_bins_from_csv(csv_dir, output_dir, grid_size, angles):
    """Call generate_proxy_model.py gravity to process ANSYS CSV -> .bin files.

    Uses pixel-centered grid + plate-normal w extraction (matching shader convention).
    """
    script = ROOT / "scripts" / "generate_proxy_model.py"
    cmd = [
        sys.executable, str(script), "gravity",
        "--source-dir", str(csv_dir),
        "--output-dir", str(output_dir),
        "--grid-size", str(grid_size),
        "--angles", *[str(int(a)) for a in angles],
    ]
    print(f"  Converting CSV -> .bin via generate_proxy_model.py gravity...")
    result = subprocess.run(cmd, cwd=str(ROOT))
    if result.returncode != 0:
        print("  ERROR: generate_proxy_model.py gravity failed", file=sys.stderr)
    return result.returncode == 0


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--bolt-layout", default="configs/bolt_layouts/7x5_default.json",
                   help="Bolt layout JSON config file (DEPRECATED: use generate_proxy_model.py gravity-ansys)")
    p.add_argument("--output-dir", default="data_proxy",
                   help="Output directory for gravity_*.bin files")
    p.add_argument("--grid-size", type=int, default=32,
                   help="Render grid resolution (default: 32)")
    p.add_argument("--angles", type=float, nargs="+", default=DEFAULT_ANGLES,
                   help="Tilt angles in degrees (default: 20 bins 10-80)")
    p.add_argument("--ansys-exe", default=ANSYS_EXE,
                   help="Path to ANSYS MAPDL executable")
    p.add_argument("--keep-temp", action="store_true",
                   help="Keep temporary ANSYS working files")
    p.add_argument("--nsubst", default="1,10,1",
                   help="NSUBST initial,max,min (default '1,10,1'; use e.g. "
                        "'50,500,50' for quasi-static branch fidelity)")
    p.add_argument("--dry-run", action="store_true",
                   help="Generate APDL files but don't run ANSYS")
    args = p.parse_args()

    # ── Load bolt layout ──
    layout_path = ROOT / args.bolt_layout
    if not layout_path.exists():
        print(f"ERROR: Bolt layout not found: {layout_path}", file=sys.stderr)
        sys.exit(1)
    layout = load_bolt_layout(str(layout_path))
    W, L = layout["plate_width_m"], layout["plate_length_m"]
    GS = args.grid_size
    positions = bolt_positions(layout)
    n_bolts = len(positions)
    print(f"=== ANSYS Gravity Bin Generator ===")
    print(f"  Layout:   {layout.get('description', args.bolt_layout)}")
    print(f"  Bolts:    {layout_utils.layout_description(layout)}")
    print(f"  Plate:    {W}x{L}m, t={layout['plate_thickness_m']*1000}mm")
    print(f"  Grid:     {GS}x{GS}")
    print(f"  Angles:   {len(args.angles)} bins, {args.angles[0]}°–{args.angles[-1]}°")
    print(f"  NSUBST:   {args.nsubst}")
    print(f"  ANSYS:    {args.ansys_exe}")
    print(f"  Output:   {args.output_dir}/")

    # ── Output directory ──
    out_dir = ROOT / args.output_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    # ── CSV output directory (feeds into precompute_gravity_bins.py) ──
    csv_dir = out_dir / "ansys_csv"
    csv_dir.mkdir(parents=True, exist_ok=True)

    # ── Process each angle ──
    failed = []
    for ang in args.angles:
        print(f"\n  [{ang:.0f}deg] ", end="", flush=True)

        work_dir = tempfile.mkdtemp(prefix=f"ansys_grav_{int(ang)}deg_",
                                    dir=str(ROOT / "build"))
        try:
            # Generate APDL
            dat_path, expected_csv = generate_apdl_input(
                layout, ang, positions, "", work_dir, nsubst=args.nsubst)

            if args.dry_run:
                print(f"APDL: {dat_path} (dry-run, skip ANSYS)")
                continue

            # Run ANSYS
            t0 = time.time()
            ok = run_ansys(dat_path, work_dir, args.ansys_exe)
            if not ok:
                failed.append(ang)
                continue

            # Verify CSV was created and copy to output dir
            if not os.path.exists(expected_csv):
                print(f"MISSING CSV: {expected_csv}", flush=True)
                failed.append(ang)
                continue

            dest_csv = csv_dir / f"node_dump_{int(ang)}deg.csv"
            import shutil
            shutil.copy(expected_csv, str(dest_csv))

            elapsed = time.time() - t0
            data = np.loadtxt(str(dest_csv), delimiter=',', skiprows=1)
            n_nodes = data.shape[0]
            uy_col = data[:, 4]
            uy_pv = (uy_col.max() - uy_col.min()) * 1000
            print(f"UY_PV={uy_pv:.1f}mm, nodes={n_nodes}, {elapsed:.0f}s", flush=True)

        finally:
            if not args.keep_temp:
                import shutil
                shutil.rmtree(work_dir, ignore_errors=True)

    print(f"\n=== ANSYS done: {len(args.angles)-len(failed)}/{len(args.angles)} angles ===")
    if failed:
        print(f"  Failed: {failed}")

    # ── Convert CSV → gravity bins ──
    if not args.dry_run:
        run_gravity_bins_from_csv(str(csv_dir), str(out_dir), GS, args.angles)

    print(f"\n  Output: {out_dir}/")
    print(f"  CSVs:   {csv_dir}/")


if __name__ == "__main__":
    main()
