#!/usr/bin/env python3
"""
Compute S95 area from flux NPY files (generated by bezier_opt.exe --dump-flux).

Pure Python — no GPU dependency. Implements the same 20-round binary search as
the C++ computeS95Level() and counts pixels above the S95 threshold.

Usage:
    # Compute S95 for all flux files in a directory
    python scripts/compute_s95_from_flux.py --flux-dir <dir> [--output <csv>]

    # Batch: run flux dump for all NEWS mirrors + surfaces, then compute S95
    python scripts/compute_s95_from_flux.py --batch --exe <path> [--config <json>]
"""

import argparse
import glob
import json
import os
import re
import subprocess
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent

# ── Receiver geometry ──
RECEIVER_RADIUS = 10.0   # m
RECEIVER_HEIGHT = 20.0   # m
PIXELS_W = 157
PIXELS_H = 50
PIXEL_AREA = (2.0 * np.pi * RECEIVER_RADIUS / PIXELS_W) * (RECEIVER_HEIGHT / PIXELS_H)


def load_flux_npy(path):
    """Load flux NPY file (50x157 float32). Returns 2D array [H, W]."""
    flux = np.load(path)  # shape: (50, 157)
    return flux


def compute_s95(flux):
    """Compute S95 area (m^2) from 2D flux array.

    Algorithm matches C++ computeS95Level():
      1. Total energy = sum(flux)
      2. Binary search (20 rounds) for threshold level
      3. Count pixels above threshold → S95 area = count * pixel_area
    """
    flat = flux.ravel().astype(np.float64)
    total = flat.sum()
    if total < 1e-6:
        return 0.0, 0.0

    # 20-round binary search for S95 threshold (matching GPU/C++ semantics)
    low, high = 0.0, float(flat.max())
    level = 0.0
    for _ in range(20):
        mid = (low + high) * 0.5
        above_sum = flat[flat > mid].sum()
        if above_sum / total > 0.95:
            low = mid
        else:
            high = mid
            # level = mid  — conservative (C++ style): use last mid below 95%
            # Actually, let's match C++: level tracks the last 'high' (=mid when <=0.95)
            # But the C++ code sets level = mid only in the "<=" branch
            pass

    # After binary search, use high as the level (conservative bound)
    level = high
    n_above = int((flat > level).sum())
    s95 = n_above * PIXEL_AREA

    return float(s95), float(level)


def parse_flux_filename(filename):
    """Parse 'Mirror_300m_sunN_flux.npy' → (mirror, sun_idx)."""
    m = re.match(r"(\w+)_(\d+)m_sun(\d+)_flux\.npy", filename)
    if m:
        return m.group(1), int(m.group(3))
    return None, None


def compute_all_s95(flux_dir):
    """Compute S95 for all NPY files in flux_dir. Returns list of dicts."""
    results = []
    pattern = os.path.join(flux_dir, "*_flux.npy")
    for fpath in sorted(glob.glob(pattern)):
        fname = os.path.basename(fpath)
        mirror, sun_idx = parse_flux_filename(fname)
        if mirror is None:
            continue
        flux = load_flux_npy(fpath)
        s95, level = compute_s95(flux)
        total_energy = flux.sum()
        results.append({
            "file": fname,
            "mirror": mirror,
            "sun_idx": sun_idx,
            "s95_m2": s95,
            "level_wm2": level,
            "total_energy": float(total_energy),
        })
    return results


def aggregate_by_mirror(results):
    """Aggregate S95 stats per mirror: mean, min, max, std."""
    from collections import defaultdict
    by_mirror = defaultdict(list)
    for r in results:
        by_mirror[r["mirror"]].append(r["s95_m2"])
    agg = {}
    for mirror, vals in by_mirror.items():
        v = np.array(vals)
        agg[mirror] = {
            "mean": float(v.mean()),
            "min": float(v.min()),
            "max": float(v.max()),
            "std": float(v.std()),
            "count": len(v),
        }
    return agg


# ══════════════════════════════════════════════════════════════════════════════
# Batch runner: orchestrates C++ flux dump + Python S95 computation
# ══════════════════════════════════════════════════════════════════════════════

MIRRORS = ["North", "East", "South", "West"]
SURFACES = ["ellipse", "tps_lsq"]


def run_batch(exe_path, config_path, surface_dir, output_base):
    """Run flux dump for all mirrors × surfaces, then compute S95."""
    all_results = []

    for mirror in MIRRORS:
        for surf_label in SURFACES:
            surface_file = os.path.join(
                surface_dir, f"{mirror}_300m_{surf_label}_surface.txt")
            if not os.path.exists(surface_file):
                print(f"  SKIP: missing surface file {surface_file}", file=sys.stderr)
                continue

            # Output sub-directory per mirror+surface to avoid filename collision
            flux_out = os.path.join(output_base, f"flux_{mirror}_{surf_label}")
            os.makedirs(flux_out, exist_ok=True)

            print(f"\n  [{mirror} {surf_label}] Running flux dump (36 suns) ...")
            cmd = [exe_path, "--dump-flux", "--surface-file", surface_file, config_path]
            # Temporarily modify config's output_dir... Hmm, that's awkward.
            # Instead, copy config and modify output_dir.
            # Simpler: use environment variable or just accept files go to config's output_dir.
            # The flux files save with heliostat name prefix, so they won't collide
            # across mirrors (North vs East etc.) but WILL collide across surfaces
            # (ellipse vs tps_lsq for the same mirror).
            #
            # Solution: run sequentially, move files after each run.
            t0 = __import__("time").time()
            result = subprocess.run(cmd, cwd=str(ROOT), capture_output=True, text=True, timeout=600)
            elapsed = __import__("time").time() - t0

            if result.returncode != 0:
                print(f"    ERROR (exit {result.returncode}): {result.stderr[-200:]}", file=sys.stderr)
                continue

            # Move flux files to sub-directory
            config_out_dir = os.path.join(output_base, "flux_dump")  # from config output_dir
            if os.path.isdir(config_out_dir):
                for f in os.listdir(config_out_dir):
                    if f.endswith("_flux.npy"):
                        src = os.path.join(config_out_dir, f)
                        dst = os.path.join(flux_out, f)
                        os.rename(src, dst)
                # Remove now-empty dir
                try:
                    os.rmdir(config_out_dir)
                except OSError:
                    pass

            print(f"    Done in {elapsed:.0f}s")

            # Compute S95 from this run
            results = compute_all_s95(flux_out)
            for r in results:
                r["surface"] = surf_label
            all_results.extend(results)

            n = len(results)
            if n > 0:
                s95_vals = [r["s95_m2"] for r in results]
                print(f"    S95: mean={np.mean(s95_vals):.2f}, "
                      f"min={np.min(s95_vals):.1f}, max={np.max(s95_vals):.1f} m2")

    return all_results


# ══════════════════════════════════════════════════════════════════════════════
# Main
# ══════════════════════════════════════════════════════════════════════════════

def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--flux-dir", default=None,
                   help="Directory containing *_flux.npy files")
    p.add_argument("--output", default=None,
                   help="Output CSV path for S95 results")
    p.add_argument("--batch", action="store_true",
                   help="Run batch flux dump + S95 computation")
    p.add_argument("--exe", default="build/src/Release/bezier_opt.exe",
                   help="Path to bezier_opt.exe (for --batch)")
    p.add_argument("--config", default="configs/flux_dump_36sun.json",
                   help="Config JSON for flux dump (for --batch)")
    p.add_argument("--surface-dir", default="validation/ellipse_tps_news",
                   help="Directory containing surface files (for --batch)")
    args = p.parse_args()

    if args.batch:
        print("=== Batch Flux Dump + S95 Computation ===\n")
        exe_path = str(ROOT / args.exe) if not os.path.isabs(args.exe) else args.exe
        config_path = str(ROOT / args.config) if not os.path.isabs(args.config) else args.config
        surface_dir = str(ROOT / args.surface_dir) if not os.path.isabs(args.surface_dir) else args.surface_dir
        output_base = surface_dir

        if not os.path.exists(exe_path):
            print(f"ERROR: exe not found: {exe_path}", file=sys.stderr)
            print(f"  Build first: cmake --build build --config Release", file=sys.stderr)
            sys.exit(1)

        all_results = run_batch(exe_path, config_path, surface_dir, output_base)

        # ── Aggregate ──
        if all_results:
            csv_path = args.output or os.path.join(output_base, "s95_summary.csv")
            with open(csv_path, "w") as f:
                f.write("mirror,surface,sun_idx,s95_m2,level_wm2,total_energy\n")
                for r in all_results:
                    f.write(f"{r['mirror']},{r['surface']},{r['sun_idx']},"
                            f"{r['s95_m2']:.3f},{r['level_wm2']:.3f},{r['total_energy']:.1f}\n")

            # Per-mirror, per-surface aggregate
            from collections import defaultdict
            by_key = defaultdict(list)
            for r in all_results:
                by_key[(r["mirror"], r["surface"])].append(r["s95_m2"])

            print(f"\n{'='*80}")
            print(f"  Annual-Average S95 Summary (36 suns)")
            print(f"{'='*80}")
            print(f"  {'Mirror':<8s} {'Ellipse S95':>12s} {'TPS-LSQ S95':>12s} {'Delta':>10s}")
            print(f"  {'-'*52}")
            for mirror in MIRRORS:
                e_vals = by_key.get((mirror, "ellipse"), [])
                t_vals = by_key.get((mirror, "tps_lsq"), [])
                e_mean = np.mean(e_vals) if e_vals else 0
                t_mean = np.mean(t_vals) if t_vals else 0
                delta = t_mean - e_mean if e_vals and t_vals else 0
                print(f"  {mirror:<8s} {e_mean:11.2f} m2 {t_mean:11.2f} m2 {delta:+9.2f} m2")
            print(f"{'='*80}")
            print(f"\n  Full results: {csv_path}")

    elif args.flux_dir:
        print(f"Computing S95 from flux files in: {args.flux_dir}")
        results = compute_all_s95(args.flux_dir)
        if not results:
            print("  No flux NPY files found.")
            return

        agg = aggregate_by_mirror(results)
        for mirror, stats in agg.items():
            print(f"  {mirror}: mean={stats['mean']:.2f}, min={stats['min']:.1f}, "
                  f"max={stats['max']:.1f}, std={stats['std']:.2f} m2 ({stats['count']} suns)")

        if args.output:
            csv_path = args.output
            with open(csv_path, "w") as f:
                f.write("file,mirror,sun_idx,s95_m2,level_wm2,total_energy\n")
                for r in results:
                    f.write(f"{r['file']},{r['mirror']},{r['sun_idx']},"
                            f"{r['s95_m2']:.3f},{r['level_wm2']:.3f},{r['total_energy']:.1f}\n")
            print(f"\n  Results saved: {csv_path}")
    else:
        p.print_help()


if __name__ == "__main__":
    main()
